// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TODO: Replace with your actual Supabase credentials from Settings → API
// Go to your new Supabase project: https://supabase.com/dashboard/project/atlgpebjqcgbusxvlura
// Then go to Settings → API to get these values

const SUPABASE_URL = "https://atlgpebjqcgbusxvlura.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bGdwZWJqcWNnYnVzeHZsdXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTQ2OTMsImV4cCI6MjA3MTk3MDY5M30.cdtHsFzomIvIMhAwuPmWnIaCFHh2SeD35_GcMNwNCiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true
    }
});

// Test connection on initialization
supabase.auth.getSession().then(({ data, error }) => {
    if (error) {
        console.error('Supabase connection error:', error);
    } else {
        console.log('Supabase connected successfully');
    }
});